# Generated by Django 5.1.3 on 2024-11-29 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('pv', models.FloatField(blank=True, db_index=True, default=0.0, help_text='Prix de vente du produit, en euros.', null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Prix de Vente')),
                ('etat', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=150, verbose_name='État')),
                ('photo', models.ImageField(height_field='image_height', max_length=255, upload_to='photos', verbose_name='IMAGE', width_field='image_width')),
                ('caracteristique', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathegory', to='produit.cathegory', verbose_name='id_cathegory')),
            ],
        ),
    ]
