# Generated by Django 5.1.3 on 2024-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
